#thymeleaf:
#    prefix=classpath: templates/
#    suffix: .html
#    check-template-location: true
#    cache: false
#  mvc:
#    static-path-pattern: "/static/**"
<<<<<<< HEAD


=======
>>>>>>> aff2bb1da86941373135a1cdbb44706dc94ba6bc
server:
 port: 8081