server:
 port: 8081
spring:
 mvc:
  pathmatch:
   matching-strategy: ant_path_matcher
 jwt:
  security:
   oauth2:
    client:
     registration:
      kakao:
       client-id: [ client-id ]
       redirect-uri: http://localhost:8080/loginKakao
       client-authentication-method: POST
       client-secret: [ secret-key ]
       authorization-grant-type:
       scope:
        - profile_nickname
        - profile_image
        - account_email
        - gender
        - birthday
       client_name: kakao
     provider:
      kakao:
       authorization-uri: https://kauth.kakao.com/oauth/authorize
       token-uri: https://kauth.kakao.com/oauth/token
       user-info-uri: https://kapi.kakao.com/v2/user/me
       user-name-attribute: id
  secret: flature!@#appleandseoullovecdafqefaaasadg
 devtools:
  livereload:
   enabled: true
  thymeleaf:
   cache: false
 datasource:
  driver-class-name: com.mysql.cj.jdbc.Driver
  url: jdbc:mysql://localhost:3306/together?serverTimezone=Asia/Seoul
  username: root
  password: tladuswns1!
 jpa:
  database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
  open-in-view: false
  show-sql: true
  hibernate:
   format_sql: true
   ddl-auto: create
logging:
 level:
  org:
   hibernate:
    SQL: DEBUG
    type:
     descriptor:
      sql:
       BasicBinder: TRACE
